# Generated by Django 2.1.5 on 2019-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
