# Generated by Django 2.1.5 on 2019-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privatekey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
