# Generated by Django 2.1.8 on 2019-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_privatekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
